shared storage and on-demand site generation
City-of-Helsinki/events-helsinki-monorepo pull request #320
Opened 2023-05-04 10:42 UTC by terovirtanen

## Description

## Issues

### Closes

**[TH-1311](https://helsinkisolutionoffice.atlassian.net/browse/TH-1311)**

### Related

## Testing

### Automated tests

### Manual testing

## Screenshots

## Additional notes

2023-05-04 10:54 UTC, terovirtanen commented
**Events-Helsinki branch is deployed to platta: https://tapahtumat-pr320.dev.hel.ninja** :rocket::rocket::rocket:

2023-05-04 10:58 UTC, terovirtanen commented
## TestCafe result is __success__ for https://tapahtumat-pr320.dev.hel.ninja :laughing::tada::tada::tada:

2023-05-04 11:53 UTC, terovirtanen commented
**Events-Helsinki branch is deployed to platta: https://tapahtumat-pr320.dev.hel.ninja** :rocket::rocket::rocket:

2023-05-04 12:13 UTC, terovirtanen commented
**Events-Helsinki branch is deployed to platta: https://tapahtumat-pr320.dev.hel.ninja** :rocket::rocket::rocket:

2023-05-04 12:31 UTC, terovirtanen commented
**Events-Helsinki branch is deployed to platta: https://tapahtumat-pr320.dev.hel.ninja** :rocket::rocket::rocket:

2023-05-08 05:32 UTC, terovirtanen commented
**Events-Helsinki branch is deployed to platta: https://tapahtumat-pr320.dev.hel.ninja** :rocket::rocket::rocket:

2023-05-08 05:36 UTC, terovirtanen commented
## TestCafe result is __success__ for https://tapahtumat-pr320.dev.hel.ninja :laughing::tada::tada::tada:

2023-05-08 05:38 UTC, terovirtanen commented
**VENUE GRAPHQL PROXY is deployed to platta: https://venue-graphql-proxy-pr320.dev.hel.ninja** :rocket::rocket::rocket:

2023-05-08 05:42 UTC, terovirtanen commented
**EVENTS GRAPHQL PROXY is deployed to platta: https://events-graphql-proxy-pr320.dev.hel.ninja** :rocket::rocket::rocket:

2023-05-08 05:44 UTC, terovirtanen commented
**Sports-Helsinki branch is deployed to platta: https://liikunta-pr320.dev.hel.ninja** :rocket::rocket::rocket:

2023-05-08 05:44 UTC, terovirtanen commented
## TestCafe result is __failed__ for https://liikunta-pr320.dev.hel.ninja :crying_cat_face::anger::boom::boom:

2023-05-08 06:44 UTC, terovirtanen commented
**Events-Helsinki branch is deployed to platta: https://tapahtumat-pr320.dev.hel.ninja** :rocket::rocket::rocket:

2023-05-08 06:48 UTC, terovirtanen commented
## TestCafe result is __success__ for https://tapahtumat-pr320.dev.hel.ninja :laughing::tada::tada::tada:

2023-05-08 06:50 UTC, terovirtanen commented
**EVENTS GRAPHQL PROXY is deployed to platta: https://events-graphql-proxy-pr320.dev.hel.ninja** :rocket::rocket::rocket:

2023-05-08 06:51 UTC, terovirtanen commented
**VENUE GRAPHQL PROXY is deployed to platta: https://venue-graphql-proxy-pr320.dev.hel.ninja** :rocket::rocket::rocket:

2023-05-08 06:57 UTC, terovirtanen commented
**Sports-Helsinki branch is deployed to platta: https://liikunta-pr320.dev.hel.ninja** :rocket::rocket::rocket:

2023-05-08 06:57 UTC, terovirtanen commented
## TestCafe result is __failed__ for https://liikunta-pr320.dev.hel.ninja :crying_cat_face::anger::boom::boom:

2023-05-09 05:18 UTC, terovirtanen commented
**Events-Helsinki branch is deployed to platta: https://tapahtumat-pr320.dev.hel.ninja** :rocket::rocket::rocket:

2023-05-09 05:22 UTC, terovirtanen commented
## TestCafe result is __success__ for https://tapahtumat-pr320.dev.hel.ninja :laughing::tada::tada::tada:

2023-05-09 05:23 UTC, terovirtanen commented
**EVENTS GRAPHQL PROXY is deployed to platta: https://events-graphql-proxy-pr320.dev.hel.ninja** :rocket::rocket::rocket:

2023-05-09 05:26 UTC, terovirtanen commented
**VENUE GRAPHQL PROXY is deployed to platta: https://venue-graphql-proxy-pr320.dev.hel.ninja** :rocket::rocket::rocket:

2023-05-09 05:27 UTC, terovirtanen commented
**Sports-Helsinki branch is deployed to platta: https://liikunta-pr320.dev.hel.ninja** :rocket::rocket::rocket:

2023-05-09 05:35 UTC, terovirtanen commented
**Events-Helsinki branch is deployed to platta: https://tapahtumat-pr320.dev.hel.ninja** :rocket::rocket::rocket:

2023-05-09 05:39 UTC, terovirtanen commented
## TestCafe result is __success__ for https://tapahtumat-pr320.dev.hel.ninja :laughing::tada::tada::tada:

2023-05-09 05:40 UTC, terovirtanen commented
**EVENTS GRAPHQL PROXY is deployed to platta: https://events-graphql-proxy-pr320.dev.hel.ninja** :rocket::rocket::rocket:

2023-05-09 05:42 UTC, terovirtanen commented
**VENUE GRAPHQL PROXY is deployed to platta: https://venue-graphql-proxy-pr320.dev.hel.ninja** :rocket::rocket::rocket:

2023-05-09 05:48 UTC, terovirtanen commented
**Sports-Helsinki branch is deployed to platta: https://liikunta-pr320.dev.hel.ninja** :rocket::rocket::rocket:

2023-05-09 05:48 UTC, terovirtanen commented
## TestCafe result is __failed__ for https://liikunta-pr320.dev.hel.ninja :crying_cat_face::anger::boom::boom:

2023-05-09 11:05 UTC, terovirtanen commented
**Events-Helsinki branch is deployed to platta: https://tapahtumat-pr320.dev.hel.ninja** :rocket::rocket::rocket:

2023-05-09 11:09 UTC, terovirtanen commented
## TestCafe result is __success__ for https://tapahtumat-pr320.dev.hel.ninja :laughing::tada::tada::tada:

2023-05-09 11:10 UTC, terovirtanen commented
**EVENTS GRAPHQL PROXY is deployed to platta: https://events-graphql-proxy-pr320.dev.hel.ninja** :rocket::rocket::rocket:

2023-05-09 11:17 UTC, terovirtanen commented
## TestCafe result is __failed__ for https://liikunta-pr320.dev.hel.ninja :crying_cat_face::anger::boom::boom:

2023-05-09 11:17 UTC, terovirtanen commented
**Sports-Helsinki branch is deployed to platta: https://liikunta-pr320.dev.hel.ninja** :rocket::rocket::rocket:

2023-05-10 06:49 UTC, terovirtanen commented
**Hobbies-Helsinki branch is deployed to platta: https://harrastukset-pr320.dev.hel.ninja** :rocket::rocket::rocket:

2023-05-10 06:49 UTC, terovirtanen commented
**Events-Helsinki branch is deployed to platta: https://tapahtumat-pr320.dev.hel.ninja** :rocket::rocket::rocket:

2023-05-10 06:52 UTC, terovirtanen commented
## TestCafe result is __success__ for https://harrastukset-pr320.dev.hel.ninja :laughing::tada::tada::tada:

2023-05-10 06:52 UTC, terovirtanen commented
**Sports-Helsinki branch is deployed to platta: https://liikunta-pr320.dev.hel.ninja** :rocket::rocket::rocket:

2023-05-10 06:53 UTC, terovirtanen commented
## TestCafe result is __success__ for https://tapahtumat-pr320.dev.hel.ninja :laughing::tada::tada::tada:

2023-05-10 06:55 UTC, terovirtanen commented
**VENUE GRAPHQL PROXY is deployed to platta: https://venue-graphql-proxy-pr320.dev.hel.ninja** :rocket::rocket::rocket:

2023-05-10 06:57 UTC, terovirtanen commented
## TestCafe result is __success__ for https://liikunta-pr320.dev.hel.ninja :laughing::tada::tada::tada:

2023-05-10 06:57 UTC, terovirtanen commented
**EVENTS GRAPHQL PROXY is deployed to platta: https://events-graphql-proxy-pr320.dev.hel.ninja** :rocket::rocket::rocket:

2023-05-11 09:55 UTC, terovirtanen commented
## TestCafe result is __success__ for https://tapahtumat-pr320.dev.hel.ninja :laughing::tada::tada::tada:

2023-05-11 09:56 UTC, terovirtanen commented
## TestCafe result is __success__ for https://harrastukset-pr320.dev.hel.ninja :laughing::tada::tada::tada:

2023-05-11 09:58 UTC, terovirtanen commented
**VENUE GRAPHQL PROXY is deployed to platta: https://venue-graphql-proxy-pr320.dev.hel.ninja** :rocket::rocket::rocket:

2023-05-11 09:59 UTC, terovirtanen commented
**EVENTS GRAPHQL PROXY is deployed to platta: https://events-graphql-proxy-pr320.dev.hel.ninja** :rocket::rocket::rocket:

2023-05-16 12:04 UTC, terovirtanen commented
**Hobbies-Helsinki branch is deployed to platta: https://harrastukset-pr320.dev.hel.ninja** :rocket::rocket::rocket:

2023-05-16 12:06 UTC, terovirtanen commented
## TestCafe result is __success__ for https://harrastukset-pr320.dev.hel.ninja :laughing::tada::tada::tada:

2023-05-16 12:08 UTC, terovirtanen commented
**Sports-Helsinki branch is deployed to platta: https://liikunta-pr320.dev.hel.ninja** :rocket::rocket::rocket:

2023-05-16 12:12 UTC, terovirtanen commented
**EVENTS GRAPHQL PROXY is deployed to platta: https://events-graphql-proxy-pr320.dev.hel.ninja** :rocket::rocket::rocket:

2023-05-16 12:12 UTC, terovirtanen commented
## TestCafe result is __success__ for https://liikunta-pr320.dev.hel.ninja :laughing::tada::tada::tada:

2023-05-17 04:29 UTC, terovirtanen commented
**Hobbies-Helsinki branch is deployed to platta: https://harrastukset-pr320.dev.hel.ninja** :rocket::rocket::rocket:

2023-05-17 04:32 UTC, terovirtanen commented
## TestCafe result is __success__ for https://harrastukset-pr320.dev.hel.ninja :laughing::tada::tada::tada:

2023-05-17 04:33 UTC, terovirtanen commented
**Sports-Helsinki branch is deployed to platta: https://liikunta-pr320.dev.hel.ninja** :rocket::rocket::rocket:

2023-05-17 04:36 UTC, terovirtanen commented
**EVENTS GRAPHQL PROXY is deployed to platta: https://events-graphql-proxy-pr320.dev.hel.ninja** :rocket::rocket::rocket:

2023-05-17 04:36 UTC, terovirtanen commented
**VENUE GRAPHQL PROXY is deployed to platta: https://venue-graphql-proxy-pr320.dev.hel.ninja** :rocket::rocket::rocket:

2023-05-17 04:37 UTC, terovirtanen commented
## TestCafe result is __success__ for https://liikunta-pr320.dev.hel.ninja :laughing::tada::tada::tada:

2023-05-17 05:05 UTC, terovirtanen commented
**Hobbies-Helsinki branch is deployed to platta: https://harrastukset-pr320.dev.hel.ninja** :rocket::rocket::rocket:

2023-05-17 05:07 UTC, terovirtanen commented
## TestCafe result is __success__ for https://harrastukset-pr320.dev.hel.ninja :laughing::tada::tada::tada:

2023-05-17 05:09 UTC, terovirtanen commented
**Sports-Helsinki branch is deployed to platta: https://liikunta-pr320.dev.hel.ninja** :rocket::rocket::rocket:

2023-05-17 05:13 UTC, terovirtanen commented
**VENUE GRAPHQL PROXY is deployed to platta: https://venue-graphql-proxy-pr320.dev.hel.ninja** :rocket::rocket::rocket:

2023-05-17 05:13 UTC, terovirtanen commented
## TestCafe result is __success__ for https://liikunta-pr320.dev.hel.ninja :laughing::tada::tada::tada:

2023-05-17 05:13 UTC, terovirtanen commented
**EVENTS GRAPHQL PROXY is deployed to platta: https://events-graphql-proxy-pr320.dev.hel.ninja** :rocket::rocket::rocket:

2023-05-17 05:29 UTC, terovirtanen commented
**Hobbies-Helsinki branch is deployed to platta: https://harrastukset-pr320.dev.hel.ninja** :rocket::rocket::rocket:

2023-05-17 05:32 UTC, terovirtanen commented
## TestCafe result is __success__ for https://harrastukset-pr320.dev.hel.ninja :laughing::tada::tada::tada:

2023-05-17 05:36 UTC, terovirtanen commented
**Sports-Helsinki branch is deployed to platta: https://liikunta-pr320.dev.hel.ninja** :rocket::rocket::rocket:

2023-05-17 05:37 UTC, terovirtanen commented
**EVENTS GRAPHQL PROXY is deployed to platta: https://events-graphql-proxy-pr320.dev.hel.ninja** :rocket::rocket::rocket:

2023-05-17 05:40 UTC, terovirtanen commented
## TestCafe result is __success__ for https://liikunta-pr320.dev.hel.ninja :laughing::tada::tada::tada:

2023-05-17 05:42 UTC, terovirtanen commented
**VENUE GRAPHQL PROXY is deployed to platta: https://venue-graphql-proxy-pr320.dev.hel.ninja** :rocket::rocket::rocket:

2023-05-17 06:06 UTC, terovirtanen commented
**Sports-Helsinki branch is deployed to platta: https://liikunta-pr320.dev.hel.ninja** :rocket::rocket::rocket:

2023-05-17 06:16 UTC, terovirtanen commented
**Events-Helsinki branch is deployed to platta: https://tapahtumat-pr320.dev.hel.ninja** :rocket::rocket::rocket:

2023-05-17 06:18 UTC, terovirtanen commented
**Sports-Helsinki branch is deployed to platta: https://liikunta-pr320.dev.hel.ninja** :rocket::rocket::rocket:

2023-05-17 06:20 UTC, terovirtanen commented
## TestCafe result is __success__ for https://tapahtumat-pr320.dev.hel.ninja :laughing::tada::tada::tada:

2023-05-17 06:22 UTC, terovirtanen commented
**EVENTS GRAPHQL PROXY is deployed to platta: https://events-graphql-proxy-pr320.dev.hel.ninja** :rocket::rocket::rocket:

2023-05-17 06:22 UTC, terovirtanen commented
## TestCafe result is __success__ for https://liikunta-pr320.dev.hel.ninja :laughing::tada::tada::tada:

2023-05-17 06:23 UTC, terovirtanen commented
**VENUE GRAPHQL PROXY is deployed to platta: https://venue-graphql-proxy-pr320.dev.hel.ninja** :rocket::rocket::rocket:

2023-05-22 04:40 UTC, terovirtanen commented
**Hobbies-Helsinki branch is deployed to platta: https://harrastukset-pr320.dev.hel.ninja** :rocket::rocket::rocket:

2023-05-22 04:43 UTC, terovirtanen commented
## TestCafe result is __success__ for https://harrastukset-pr320.dev.hel.ninja :laughing::tada::tada::tada:

2023-05-22 04:44 UTC, terovirtanen commented
**Events-Helsinki branch is deployed to platta: https://tapahtumat-pr320.dev.hel.ninja** :rocket::rocket::rocket:

2023-05-22 04:45 UTC, terovirtanen commented
**Sports-Helsinki branch is deployed to platta: https://liikunta-pr320.dev.hel.ninja** :rocket::rocket::rocket:

2023-05-22 04:47 UTC, terovirtanen commented
## TestCafe result is __success__ for https://tapahtumat-pr320.dev.hel.ninja :laughing::tada::tada::tada:

2023-05-22 04:48 UTC, terovirtanen commented
**VENUE GRAPHQL PROXY is deployed to platta: https://venue-graphql-proxy-pr320.dev.hel.ninja** :rocket::rocket::rocket:

2023-05-22 04:48 UTC, terovirtanen commented
## TestCafe result is __success__ for https://liikunta-pr320.dev.hel.ninja :laughing::tada::tada::tada:

2023-05-22 04:49 UTC, terovirtanen commented
**EVENTS GRAPHQL PROXY is deployed to platta: https://events-graphql-proxy-pr320.dev.hel.ninja** :rocket::rocket::rocket:

2023-05-22 07:13 UTC, terovirtanen commented
**Hobbies-Helsinki branch is deployed to platta: https://harrastukset-pr320.dev.hel.ninja** :rocket::rocket::rocket:

2023-05-22 07:17 UTC, terovirtanen commented
## TestCafe result is __success__ for https://harrastukset-pr320.dev.hel.ninja :laughing::tada::tada::tada:

2023-05-22 07:20 UTC, terovirtanen commented
**Events-Helsinki branch is deployed to platta: https://tapahtumat-pr320.dev.hel.ninja** :rocket::rocket::rocket:

2023-05-22 07:22 UTC, terovirtanen commented
**VENUE GRAPHQL PROXY is deployed to platta: https://venue-graphql-proxy-pr320.dev.hel.ninja** :rocket::rocket::rocket:

2023-05-22 07:22 UTC, terovirtanen commented
**EVENTS GRAPHQL PROXY is deployed to platta: https://events-graphql-proxy-pr320.dev.hel.ninja** :rocket::rocket::rocket:

2023-05-22 07:23 UTC, terovirtanen commented
**Sports-Helsinki branch is deployed to platta: https://liikunta-pr320.dev.hel.ninja** :rocket::rocket::rocket:

2023-05-22 07:23 UTC, terovirtanen commented
## TestCafe result is __success__ for https://tapahtumat-pr320.dev.hel.ninja :laughing::tada::tada::tada:

2023-05-22 07:28 UTC, terovirtanen commented
## TestCafe result is __success__ for https://liikunta-pr320.dev.hel.ninja :laughing::tada::tada::tada:

2023-05-22 08:04 UTC, terovirtanen commented
**Hobbies-Helsinki branch is deployed to platta: https://harrastukset-pr320.dev.hel.ninja** :rocket::rocket::rocket:

2023-05-22 08:09 UTC, terovirtanen commented
**VENUE GRAPHQL PROXY is deployed to platta: https://venue-graphql-proxy-pr320.dev.hel.ninja** :rocket::rocket::rocket:

2023-05-22 08:09 UTC, terovirtanen commented
**Sports-Helsinki branch is deployed to platta: https://liikunta-pr320.dev.hel.ninja** :rocket::rocket::rocket:

2023-05-22 08:14 UTC, terovirtanen commented
**Hobbies-Helsinki branch is deployed to platta: https://harrastukset-pr320.dev.hel.ninja** :rocket::rocket::rocket:

2023-05-22 08:18 UTC, terovirtanen commented
## TestCafe result is __success__ for https://harrastukset-pr320.dev.hel.ninja :laughing::tada::tada::tada:

2023-05-22 08:18 UTC, terovirtanen commented
**Events-Helsinki branch is deployed to platta: https://tapahtumat-pr320.dev.hel.ninja** :rocket::rocket::rocket:

2023-05-22 08:20 UTC, terovirtanen commented
**Sports-Helsinki branch is deployed to platta: https://liikunta-pr320.dev.hel.ninja** :rocket::rocket::rocket:

2023-05-22 08:22 UTC, terovirtanen commented
## TestCafe result is __success__ for https://tapahtumat-pr320.dev.hel.ninja :laughing::tada::tada::tada:

2023-05-22 10:19 UTC, terovirtanen commented
## TestCafe result is __success__ for https://harrastukset-pr320.dev.hel.ninja :laughing::tada::tada::tada:

2023-05-22 10:23 UTC, terovirtanen commented
**EVENTS GRAPHQL PROXY is deployed to platta: https://events-graphql-proxy-pr320.dev.hel.ninja** :rocket::rocket::rocket:

2023-05-22 10:23 UTC, terovirtanen commented
**VENUE GRAPHQL PROXY is deployed to platta: https://venue-graphql-proxy-pr320.dev.hel.ninja** :rocket::rocket::rocket:

2023-05-22 10:23 UTC, terovirtanen commented
## TestCafe result is __success__ for https://tapahtumat-pr320.dev.hel.ninja :laughing::tada::tada::tada:

2023-05-22 10:23 UTC, terovirtanen commented
**Sports-Helsinki branch is deployed to platta: https://liikunta-pr320.dev.hel.ninja** :rocket::rocket::rocket:

2023-05-22 10:27 UTC, terovirtanen commented
## TestCafe result is __success__ for https://liikunta-pr320.dev.hel.ninja :laughing::tada::tada::tada:

2023-05-23 04:21 UTC, terovirtanen commented
**Hobbies-Helsinki branch is deployed to platta: https://harrastukset-pr320.dev.hel.ninja** :rocket::rocket::rocket:

2023-05-23 04:24 UTC, terovirtanen commented
## TestCafe result is __success__ for https://harrastukset-pr320.dev.hel.ninja :laughing::tada::tada::tada:

2023-05-23 04:24 UTC, terovirtanen commented
**Events-Helsinki branch is deployed to platta: https://tapahtumat-pr320.dev.hel.ninja** :rocket::rocket::rocket:

2023-05-23 04:26 UTC, terovirtanen commented
**Sports-Helsinki branch is deployed to platta: https://liikunta-pr320.dev.hel.ninja** :rocket::rocket::rocket:

2023-05-23 04:29 UTC, terovirtanen commented
## TestCafe result is __success__ for https://tapahtumat-pr320.dev.hel.ninja :laughing::tada::tada::tada:

2023-05-23 04:29 UTC, terovirtanen commented
**EVENTS GRAPHQL PROXY is deployed to platta: https://events-graphql-proxy-pr320.dev.hel.ninja** :rocket::rocket::rocket:

2023-05-23 04:30 UTC, terovirtanen commented
**VENUE GRAPHQL PROXY is deployed to platta: https://venue-graphql-proxy-pr320.dev.hel.ninja** :rocket::rocket::rocket:

2023-05-23 07:15 UTC, terovirtanen commented
**Hobbies-Helsinki branch is deployed to platta: https://harrastukset-pr320.dev.hel.ninja** :rocket::rocket::rocket:

2023-05-23 07:18 UTC, terovirtanen commented
## TestCafe result is __success__ for https://harrastukset-pr320.dev.hel.ninja :laughing::tada::tada::tada:

2023-05-23 07:20 UTC, terovirtanen commented
**Events-Helsinki branch is deployed to platta: https://tapahtumat-pr320.dev.hel.ninja** :rocket::rocket::rocket:

2023-05-23 07:20 UTC, terovirtanen commented
**Sports-Helsinki branch is deployed to platta: https://liikunta-pr320.dev.hel.ninja** :rocket::rocket::rocket:

2023-05-23 07:23 UTC, terovirtanen commented
**EVENTS GRAPHQL PROXY is deployed to platta: https://events-graphql-proxy-pr320.dev.hel.ninja** :rocket::rocket::rocket:

2023-05-23 07:24 UTC, terovirtanen commented
## TestCafe result is __success__ for https://tapahtumat-pr320.dev.hel.ninja :laughing::tada::tada::tada:

2023-05-23 07:24 UTC, terovirtanen commented
**VENUE GRAPHQL PROXY is deployed to platta: https://venue-graphql-proxy-pr320.dev.hel.ninja** :rocket::rocket::rocket:

2023-05-23 07:24 UTC, terovirtanen commented
## TestCafe result is __success__ for https://liikunta-pr320.dev.hel.ninja :laughing::tada::tada::tada:

2023-05-23 07:41 UTC, terovirtanen commented
**Hobbies-Helsinki branch is deployed to platta: https://harrastukset-pr320.dev.hel.ninja** :rocket::rocket::rocket:

2023-05-23 07:45 UTC, terovirtanen commented
## TestCafe result is __success__ for https://harrastukset-pr320.dev.hel.ninja :laughing::tada::tada::tada:

2023-05-23 07:46 UTC, terovirtanen commented
**Events-Helsinki branch is deployed to platta: https://tapahtumat-pr320.dev.hel.ninja** :rocket::rocket::rocket:

2023-05-23 07:48 UTC, terovirtanen commented
**Sports-Helsinki branch is deployed to platta: https://liikunta-pr320.dev.hel.ninja** :rocket::rocket::rocket:

2023-05-23 07:50 UTC, terovirtanen commented
**EVENTS GRAPHQL PROXY is deployed to platta: https://events-graphql-proxy-pr320.dev.hel.ninja** :rocket::rocket::rocket:

2023-05-23 07:50 UTC, terovirtanen commented
## TestCafe result is __success__ for https://tapahtumat-pr320.dev.hel.ninja :laughing::tada::tada::tada:

2023-05-23 07:51 UTC, terovirtanen commented
**VENUE GRAPHQL PROXY is deployed to platta: https://venue-graphql-proxy-pr320.dev.hel.ninja** :rocket::rocket::rocket:

2023-05-23 07:51 UTC, terovirtanen commented
## TestCafe result is __success__ for https://liikunta-pr320.dev.hel.ninja :laughing::tada::tada::tada:

2023-05-23 08:23 UTC, terovirtanen commented
**Hobbies-Helsinki branch is deployed to platta: https://harrastukset-pr320.dev.hel.ninja** :rocket::rocket::rocket:

2023-05-23 08:26 UTC, terovirtanen commented
**Events-Helsinki branch is deployed to platta: https://tapahtumat-pr320.dev.hel.ninja** :rocket::rocket::rocket:

2023-05-23 08:26 UTC, terovirtanen commented
## TestCafe result is __success__ for https://harrastukset-pr320.dev.hel.ninja :laughing::tada::tada::tada:

2023-05-23 08:28 UTC, terovirtanen commented
**Sports-Helsinki branch is deployed to platta: https://liikunta-pr320.dev.hel.ninja** :rocket::rocket::rocket:

2023-05-23 08:30 UTC, terovirtanen commented
## TestCafe result is __success__ for https://tapahtumat-pr320.dev.hel.ninja :laughing::tada::tada::tada:

2023-05-23 08:31 UTC, terovirtanen commented
**EVENTS GRAPHQL PROXY is deployed to platta: https://events-graphql-proxy-pr320.dev.hel.ninja** :rocket::rocket::rocket:

2023-05-23 08:31 UTC, terovirtanen commented
**VENUE GRAPHQL PROXY is deployed to platta: https://venue-graphql-proxy-pr320.dev.hel.ninja** :rocket::rocket::rocket:

2023-05-23 10:23 UTC, terovirtanen commented
**Hobbies-Helsinki branch is deployed to platta: https://harrastukset-pr320.dev.hel.ninja** :rocket::rocket::rocket:

2023-05-23 10:26 UTC, terovirtanen commented
**Events-Helsinki branch is deployed to platta: https://tapahtumat-pr320.dev.hel.ninja** :rocket::rocket::rocket:

2023-05-23 10:28 UTC, terovirtanen commented
**Sports-Helsinki branch is deployed to platta: https://liikunta-pr320.dev.hel.ninja** :rocket::rocket::rocket:

2023-05-23 10:29 UTC, terovirtanen commented
## TestCafe result is __failed__ for https://harrastukset-pr320.dev.hel.ninja :crying_cat_face::anger::boom::boom:

2023-05-23 10:30 UTC, terovirtanen commented
**VENUE GRAPHQL PROXY is deployed to platta: https://venue-graphql-proxy-pr320.dev.hel.ninja** :rocket::rocket::rocket:

2023-05-23 10:31 UTC, terovirtanen commented
## TestCafe result is __success__ for https://tapahtumat-pr320.dev.hel.ninja :laughing::tada::tada::tada:

2023-05-23 10:32 UTC, terovirtanen commented
## TestCafe result is __success__ for https://liikunta-pr320.dev.hel.ninja :laughing::tada::tada::tada:

2023-05-23 10:34 UTC, terovirtanen commented
**EVENTS GRAPHQL PROXY is deployed to platta: https://events-graphql-proxy-pr320.dev.hel.ninja** :rocket::rocket::rocket:

2023-05-24 12:08 UTC, terovirtanen commented
## TestCafe result is __success__ for https://harrastukset-pr320.dev.hel.ninja :laughing::tada::tada::tada:

2023-05-24 12:11 UTC, terovirtanen commented
**VENUE GRAPHQL PROXY is deployed to platta: https://venue-graphql-proxy-pr320.dev.hel.ninja** :rocket::rocket::rocket:

2023-05-24 12:11 UTC, terovirtanen commented
**Events-Helsinki branch is deployed to platta: https://tapahtumat-pr320.dev.hel.ninja** :rocket::rocket::rocket:

2023-05-24 12:11 UTC, terovirtanen commented
**Sports-Helsinki branch is deployed to platta: https://liikunta-pr320.dev.hel.ninja** :rocket::rocket::rocket:

2023-05-24 12:15 UTC, terovirtanen commented
## TestCafe result is __success__ for https://liikunta-pr320.dev.hel.ninja :laughing::tada::tada::tada:

2023-05-24 12:15 UTC, terovirtanen commented
## TestCafe result is __success__ for https://tapahtumat-pr320.dev.hel.ninja :laughing::tada::tada::tada:

2023-05-25 06:49 UTC, terovirtanen commented on apps/events-helsinki/src/pages/api/revalidate.ts
> +    const articlePageInfos = await getAllArticles(eventsApolloClient);
filter duplicate pages and articles, draft issue is problem on CMS

2023-05-25 06:49 UTC, terovirtanen commented on apps/events-helsinki/src/pages/api/revalidate.ts
> +  if (req.query.secret !== process.env.REVALIDATE_TOKEN) {
done

2023-05-25 06:50 UTC, terovirtanen commented on apps/events-helsinki/src/pages/api/revalidate.ts
> +import { getAllArticles, getAllPages } from '@events-helsinki/components';
it seems to be more complicate as assumed, it will do on different task

2023-05-25 07:05 UTC, terovirtanen commented
**Federation Router branch is deployed to platta: https://events-graphql-federation-hobbies-pr320.dev.hel.ninja** :rocket::rocket::rocket:

2023-05-25 07:07 UTC, terovirtanen commented
**Federation Router branch is deployed to platta: https://events-graphql-federation-events-pr320.dev.hel.ninja** :rocket::rocket::rocket:

2023-05-25 07:07 UTC, terovirtanen commented
**Federation Router branch is deployed to platta: https://events-graphql-federation-sports-pr320.dev.hel.ninja** :rocket::rocket::rocket:

2023-05-25 07:12 UTC, terovirtanen commented
**Hobbies-Helsinki branch is deployed to platta: https://harrastukset-pr320.dev.hel.ninja** :rocket::rocket::rocket:

2023-05-25 07:16 UTC, terovirtanen commented
**Events-Helsinki branch is deployed to platta: https://tapahtumat-pr320.dev.hel.ninja** :rocket::rocket::rocket:

2023-05-25 07:17 UTC, terovirtanen commented
**EVENTS GRAPHQL PROXY is deployed to platta: https://events-graphql-proxy-pr320.dev.hel.ninja** :rocket::rocket::rocket:

2023-05-25 07:18 UTC, terovirtanen commented
**VENUE GRAPHQL PROXY is deployed to platta: https://venue-graphql-proxy-pr320.dev.hel.ninja** :rocket::rocket::rocket:

2023-05-25 07:19 UTC, terovirtanen commented
**Sports-Helsinki branch is deployed to platta: https://liikunta-pr320.dev.hel.ninja** :rocket::rocket::rocket:

2023-05-25 07:21 UTC, terovirtanen commented
## TestCafe result is __success__ for https://tapahtumat-pr320.dev.hel.ninja :laughing::tada::tada::tada:

2023-05-25 07:22 UTC, terovirtanen commented
## TestCafe result is __success__ for https://liikunta-pr320.dev.hel.ninja :laughing::tada::tada::tada:

2023-05-26 06:46 UTC, nikomakela reviewed
There are some minor inconsistensies, which makes it hard to understand what really happens, but I guess we could try this now. As an example, I would clean the getStaticProps so that they never return any paths. Now, if I run a docker-container locally (`yarn docker:events:serve`), it will generate the static pages on build time. If, e.g. the `SKIP_BUILD_STATIC_GENERATION==true` env-variable is or would be taken in use, it wouldn't affect anyhow to the current version of the front page, which is SSR-rendered, but not a statically served path. **I think this issues must be addressesed asap, but I'll approve this PR so we can test the implementation in the real Platta-test-env.**

Also, in my PR which was linked to this, had the more effecient request to fetch all the paths of the articles and pages, which also made it more clear that we are only interested about the uris. Other syntax sugar was added there too.

I tried to test this PR by running te build with `SKIP_BUILD_STATIC_GENERATION=1 yarn docker:events:build --no-cache`. The --no-cache was needed, because otherwise it always fetched the container image that had the static paths revalidation included from the cache. But, it still didn't work!

2023-05-26 06:52 UTC, nikomakela requested changes
Only the post requests should be allowed, so the request handling would not be automatically cached by the server. The request would store the secret-parameter, which we don't want to be written in the logs for example.

2023-05-26 07:35 UTC, terovirtanen commented
**Federation Router branch is deployed to platta: https://events-graphql-federation-hobbies-pr320.dev.hel.ninja** :rocket::rocket::rocket:

2023-05-26 07:37 UTC, terovirtanen commented
**Federation Router branch is deployed to platta: https://events-graphql-federation-events-pr320.dev.hel.ninja** :rocket::rocket::rocket:

2023-05-26 07:38 UTC, terovirtanen commented
**Federation Router branch is deployed to platta: https://events-graphql-federation-sports-pr320.dev.hel.ninja** :rocket::rocket::rocket:

2023-05-26 07:39 UTC, terovirtanen commented
**Hobbies-Helsinki branch is deployed to platta: https://harrastukset-pr320.dev.hel.ninja** :rocket::rocket::rocket:

2023-05-26 07:42 UTC, terovirtanen commented
## TestCafe result is __success__ for https://harrastukset-pr320.dev.hel.ninja :laughing::tada::tada::tada:

2023-05-26 07:44 UTC, terovirtanen commented
**Sports-Helsinki branch is deployed to platta: https://liikunta-pr320.dev.hel.ninja** :rocket::rocket::rocket:

2023-05-26 07:47 UTC, terovirtanen commented
## TestCafe result is __success__ for https://tapahtumat-pr320.dev.hel.ninja :laughing::tada::tada::tada:

2023-05-26 07:48 UTC, terovirtanen commented
**EVENTS GRAPHQL PROXY is deployed to platta: https://events-graphql-proxy-pr320.dev.hel.ninja** :rocket::rocket::rocket:

2023-05-26 07:48 UTC, terovirtanen commented
## TestCafe result is __success__ for https://liikunta-pr320.dev.hel.ninja :laughing::tada::tada::tada:

2023-05-26 07:51 UTC, terovirtanen commented
**Federation Router branch is deployed to platta: https://events-graphql-federation-hobbies-pr320.dev.hel.ninja** :rocket::rocket::rocket:

2023-05-26 07:53 UTC, terovirtanen commented
**Federation Router branch is deployed to platta: https://events-graphql-federation-sports-pr320.dev.hel.ninja** :rocket::rocket::rocket:

2023-05-26 07:53 UTC, terovirtanen commented
**Federation Router branch is deployed to platta: https://events-graphql-federation-events-pr320.dev.hel.ninja** :rocket::rocket::rocket:

2023-05-26 07:56 UTC, terovirtanen commented
**Hobbies-Helsinki branch is deployed to platta: https://harrastukset-pr320.dev.hel.ninja** :rocket::rocket::rocket:

2023-05-26 07:57 UTC, terovirtanen commented
**Events-Helsinki branch is deployed to platta: https://tapahtumat-pr320.dev.hel.ninja** :rocket::rocket::rocket:

2023-05-26 07:59 UTC, terovirtanen commented
## TestCafe result is __success__ for https://harrastukset-pr320.dev.hel.ninja :laughing::tada::tada::tada:

2023-05-26 08:00 UTC, terovirtanen commented
**Sports-Helsinki branch is deployed to platta: https://liikunta-pr320.dev.hel.ninja** :rocket::rocket::rocket:

2023-05-26 08:01 UTC, nikomakela approved these changes

2023-05-26 08:01 UTC, terovirtanen commented
## TestCafe result is __success__ for https://tapahtumat-pr320.dev.hel.ninja :laughing::tada::tada::tada:

2023-05-26 08:03 UTC, terovirtanen commented
## TestCafe result is __success__ for https://liikunta-pr320.dev.hel.ninja :laughing::tada::tada::tada:

2023-05-26 08:03 UTC, nikomakela commented
Sonarcloud found a bug related to the async function usage. Await must be added. https://sonarcloud.io/project/issues?resolved=false&types=BUG&pullRequest=320&id=City-of-Helsinki_tapahtumat-ui&open=AYhHtO9XlIsKvqj8qnAN

2023-05-26 08:03 UTC, terovirtanen commented
**VENUE GRAPHQL PROXY is deployed to platta: https://venue-graphql-proxy-pr320.dev.hel.ninja** :rocket::rocket::rocket:

2023-05-26 08:03 UTC, terovirtanen commented
**EVENTS GRAPHQL PROXY is deployed to platta: https://events-graphql-proxy-pr320.dev.hel.ninja** :rocket::rocket::rocket:

2023-05-26 08:29 UTC, terovirtanen commented
**Federation Router branch is deployed to platta: https://events-graphql-federation-hobbies-pr320.dev.hel.ninja** :rocket::rocket::rocket:

2023-05-26 08:32 UTC, terovirtanen commented
**Federation Router branch is deployed to platta: https://events-graphql-federation-events-pr320.dev.hel.ninja** :rocket::rocket::rocket:

2023-05-26 08:32 UTC, terovirtanen commented
**Federation Router branch is deployed to platta: https://events-graphql-federation-sports-pr320.dev.hel.ninja** :rocket::rocket::rocket:

2023-05-26 08:32 UTC, terovirtanen commented
**Hobbies-Helsinki branch is deployed to platta: https://harrastukset-pr320.dev.hel.ninja** :rocket::rocket::rocket:

2023-05-26 08:36 UTC, terovirtanen commented
## TestCafe result is __success__ for https://harrastukset-pr320.dev.hel.ninja :laughing::tada::tada::tada:

2023-05-26 08:36 UTC, terovirtanen commented
**Events-Helsinki branch is deployed to platta: https://tapahtumat-pr320.dev.hel.ninja** :rocket::rocket::rocket:

2023-05-26 08:38 UTC, terovirtanen commented
**Sports-Helsinki branch is deployed to platta: https://liikunta-pr320.dev.hel.ninja** :rocket::rocket::rocket:

2023-05-26 08:41 UTC, terovirtanen commented
## TestCafe result is __success__ for https://tapahtumat-pr320.dev.hel.ninja :laughing::tada::tada::tada:

2023-05-26 08:41 UTC, terovirtanen commented
**VENUE GRAPHQL PROXY is deployed to platta: https://venue-graphql-proxy-pr320.dev.hel.ninja** :rocket::rocket::rocket:

2023-05-26 08:41 UTC, terovirtanen commented
## TestCafe result is __success__ for https://liikunta-pr320.dev.hel.ninja :laughing::tada::tada::tada:

2023-05-26 08:44 UTC, terovirtanen commented
**EVENTS GRAPHQL PROXY is deployed to platta: https://events-graphql-proxy-pr320.dev.hel.ninja** :rocket::rocket::rocket:

2023-05-26 09:49 UTC, terovirtanen commented
**Federation Router branch is deployed to platta: https://events-graphql-federation-hobbies-pr320.dev.hel.ninja** :rocket::rocket::rocket:

2023-05-26 09:53 UTC, terovirtanen commented
**Federation Router branch is deployed to platta: https://events-graphql-federation-sports-pr320.dev.hel.ninja** :rocket::rocket::rocket:

2023-05-26 09:53 UTC, terovirtanen commented
**Federation Router branch is deployed to platta: https://events-graphql-federation-events-pr320.dev.hel.ninja** :rocket::rocket::rocket:

2023-05-26 09:54 UTC, terovirtanen commented
**Hobbies-Helsinki branch is deployed to platta: https://harrastukset-pr320.dev.hel.ninja** :rocket::rocket::rocket:

2023-05-26 09:57 UTC, terovirtanen commented
## TestCafe result is __success__ for https://harrastukset-pr320.dev.hel.ninja :laughing::tada::tada::tada:

2023-05-26 09:57 UTC, terovirtanen commented
**Events-Helsinki branch is deployed to platta: https://tapahtumat-pr320.dev.hel.ninja** :rocket::rocket::rocket:

2023-05-26 09:59 UTC, terovirtanen commented
**Sports-Helsinki branch is deployed to platta: https://liikunta-pr320.dev.hel.ninja** :rocket::rocket::rocket:

2023-05-26 10:01 UTC, terovirtanen commented
## TestCafe result is __success__ for https://tapahtumat-pr320.dev.hel.ninja :laughing::tada::tada::tada:

2023-05-26 10:02 UTC, terovirtanen commented
**EVENTS GRAPHQL PROXY is deployed to platta: https://events-graphql-proxy-pr320.dev.hel.ninja** :rocket::rocket::rocket:

2023-05-26 10:02 UTC, terovirtanen commented
**VENUE GRAPHQL PROXY is deployed to platta: https://venue-graphql-proxy-pr320.dev.hel.ninja** :rocket::rocket::rocket:

2023-05-26 10:06 UTC, terovirtanen commented
**Federation Router branch is deployed to platta: https://events-graphql-federation-hobbies-pr320.dev.hel.ninja** :rocket::rocket::rocket:

2023-05-26 10:11 UTC, terovirtanen commented
**Hobbies-Helsinki branch is deployed to platta: https://harrastukset-pr320.dev.hel.ninja** :rocket::rocket::rocket:

2023-05-26 10:12 UTC, terovirtanen commented
**Federation Router branch is deployed to platta: https://events-graphql-federation-sports-pr320.dev.hel.ninja** :rocket::rocket::rocket:

2023-05-26 10:12 UTC, terovirtanen commented
**Federation Router branch is deployed to platta: https://events-graphql-federation-events-pr320.dev.hel.ninja** :rocket::rocket::rocket:

2023-05-26 10:14 UTC, terovirtanen commented
## TestCafe result is __success__ for https://harrastukset-pr320.dev.hel.ninja :laughing::tada::tada::tada:

2023-05-26 10:15 UTC, terovirtanen commented
**Events-Helsinki branch is deployed to platta: https://tapahtumat-pr320.dev.hel.ninja** :rocket::rocket::rocket:

2023-05-26 10:16 UTC, terovirtanen commented
**Sports-Helsinki branch is deployed to platta: https://liikunta-pr320.dev.hel.ninja** :rocket::rocket::rocket:

2023-05-26 10:19 UTC, terovirtanen commented
## TestCafe result is __success__ for https://tapahtumat-pr320.dev.hel.ninja :laughing::tada::tada::tada:

2023-05-26 10:19 UTC, terovirtanen commented
**EVENTS GRAPHQL PROXY is deployed to platta: https://events-graphql-proxy-pr320.dev.hel.ninja** :rocket::rocket::rocket:

2023-05-26 10:20 UTC, terovirtanen commented
## TestCafe result is __success__ for https://liikunta-pr320.dev.hel.ninja :laughing::tada::tada::tada:

2023-05-26 10:21 UTC, terovirtanen commented
**VENUE GRAPHQL PROXY is deployed to platta: https://venue-graphql-proxy-pr320.dev.hel.ninja** :rocket::rocket::rocket:

2023-05-26 10:35 UTC, merged