TH-1334 | Remove back button
City-of-Helsinki/events-helsinki-monorepo pull request #756
Opened 2024-12-19 11:47 UTC by melniiv

## Description
When there is no return url, the back button should be hidden

## Issues

### Closes

**[DEV-XXX](https://helsinkisolutionoffice.atlassian.net/browse/DEV-XXX):**

### Related

## Testing

### Automated tests

### Manual testing

## Screenshots

## Additional notes

2024-12-19 12:11 UTC, terovirtanen commented
**Events-Helsinki branch is deployed to platta: https://tapahtumat-pr756.dev.hel.ninja** :rocket::rocket::rocket:

2024-12-19 12:12 UTC, terovirtanen commented
**Sports-Helsinki branch is deployed to platta: https://liikunta-pr756.dev.hel.ninja** :rocket::rocket::rocket:

2024-12-19 12:16 UTC, terovirtanen commented
## TestCafe result is __success__ for https://liikunta-pr756.dev.hel.ninja :laughing::tada::tada::tada:

2024-12-19 12:16 UTC, terovirtanen commented
**Hobbies-Helsinki branch is deployed to platta: https://harrastukset-pr756.dev.hel.ninja** :rocket::rocket::rocket:

2024-12-19 12:16 UTC, terovirtanen commented
## TestCafe result is __success__ for https://tapahtumat-pr756.dev.hel.ninja :laughing::tada::tada::tada:

2024-12-19 12:22 UTC, terovirtanen commented
## TestCafe result is __success__ for https://harrastukset-pr756.dev.hel.ninja :laughing::tada::tada::tada:

2024-12-19 12:56 UTC, nikomakela approved these changes

2024-12-19 13:11 UTC, nikomakela requested changes
ACtually, I think we need to reconsider this a bit, because when I tested the current production environment, I found couple of issues.

When using a laptop browser:
1. Using hero back button, I'm first taken to the right card, the card that I clicked earlier, but then the page scroll is resetted and I'mtaken to top of the page.
2. If I use browser back button, I'm always taken to the top of the page.

When using laptop in mobile view emulation:
1. The screen is white for really long and flashes multiple times. Then I'm taken to the top of the page. No matter what go back -feature I'm using.

When using a mobile phone:
1. The hero back button works as expected and I'm taken to the card that I clicked.
2. The browser back button always takes me to top of the page.

So, if we try to get rid of the back button, I think we first need to fix these broken features and test this properly.

2025-01-03 09:50 UTC, karisal-anders commented
> ACtually, I think we need to reconsider this a bit, because when I tested the current production environment, I found couple of issues.
> 
> When using a laptop browser:
> 
> 1. Using hero back button, I'm first taken to the right card, the card that I clicked earlier, but then the page scroll is resetted and I'mtaken to top of the page.
> 2. If I use browser back button, I'm always taken to the top of the page.
> 
> When using laptop in mobile view emulation:
> 
> 1. The screen is white for really long and flashes multiple times. Then I'm taken to the top of the page. No matter what go back -feature I'm using.
> 
> When using a mobile phone:
> 
> 1. The hero back button works as expected and I'm taken to the card that I clicked.
> 2. The browser back button always takes me to top of the page.
> 
> So, if we try to get rid of the back button, I think we first need to fix these broken features and test this properly.

Looks like there's quite a bit to do before this can be merged. I remove myself as a reviewer to make my review request list more of an actionable TODO-list and this doesn't qualify taking into account also that [TH-1334](https://helsinkisolutionoffice.atlassian.net/browse/TH-1334) isn't in the sprint. If this is taken under work later, then review can be requested again.

2025-11-04 11:06 UTC, closed without merging